services:
  tts-api:
    build: .
    volumes:
      - ./api:/app/api
      - ./lib:/app/lib
      - ./audio:/app/audio
      - ./tts-model-cache:/root/.local/share/tts
      - db_data:/app/data
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./data/audio.db
    ports:
      - "8000:8000"

volumes:
  db_data:
