services:
  tts-api:
    build: .
    volumes:
      - ./app:/app/api
      - ./lib:/app/lib
      - ./audio:/app/audio
      - ./tts-model-cache:/root/.local/share/tts
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///audio.db
    ports:
      - "8000:8000"
